### ISSUE TITLE
All icons are black

### ISSUE THREAD

**Issue by LarryAngama** [P3N-101/ResourceKit#1]
All icons are displayed in black no way to display them 
![black](https://github.com/P3N-101/ResourceKit/assets/12730165/c8640169-4780-4d0f-83dc-7e789be1c9ce)

**Comment by P3N-101** [comment]
Hi, you need to enable to PCF Components for Canvas apps, in admin.

powerplatform.microsoft.com select the environment and go to Settings --> Product --> Features and enable it.

![enablepcf](https://github.com/P3N-101/ResourceKit/assets/70491094/eedeb438-6ecf-44c2-959c-890e868ca1c8)

**Comment by P3N-101** [comment]
Let me know if you still have any issues.

**Comment by LarryAngama** [comment]
Hi, I still have the issue I activate the feature 2 days ago.

**Comment by LarryAngama** [comment]
Hi, I still have the issue I activate the feature 2 days ago.

**Comment by P3N-101** [comment]
Have you installed the Pre-requisites?
